// Code generated by 'github.com/streamingfast/firehose-core/proto/generator', DO NOT EDIT!
package wkp

func init() {
	// https://buf.build/streamingfast/firehose-tron/docs/55d8eaba13194171b3390f83bf8088d0:google.protobuf
	register("google/protobuf/any.proto", &WellKnownProto{
		FileDescriptor: "Chlnb29nbGUvcHJvdG9idWYvYW55LnByb3RvEg9nb29nbGUucHJvdG9idWYiNgoDQW55EhkKCHR5cGVfdXJsGAEgASgJUgd0eXBlVXJsEhQKBXZhbHVlGAIgASgMUgV2YWx1ZUJ2ChNjb20uZ29vZ2xlLnByb3RvYnVmQghBbnlQcm90b1ABWixnb29nbGUuZ29sYW5nLm9yZy9wcm90b2J1Zi90eXBlcy9rbm93bi9hbnlwYqICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxsS25vd25UeXBlc2IGcHJvdG8z",
	})
}