// Code generated by 'github.com/streamingfast/firehose-core/proto/generator', DO NOT EDIT!
package wkp

func init() {
	// https://buf.build/streamingfast/firehose-cosmos/docs/453eb75cabe64abcb4a559f47bcb7e9a:google.protobuf
	register("google/protobuf/duration.proto", &WellKnownProto{
		FileDescriptor: "Ch5nb29nbGUvcHJvdG9idWYvZHVyYXRpb24ucHJvdG8SD2dvb2dsZS5wcm90b2J1ZiI6CghEdXJhdGlvbhIYCgdzZWNvbmRzGAEgASgDUgdzZWNvbmRzEhQKBW5hbm9zGAIgASgFUgVuYW5vc0KDAQoTY29tLmdvb2dsZS5wcm90b2J1ZkINRHVyYXRpb25Qcm90b1ABWjFnb29nbGUuZ29sYW5nLm9yZy9wcm90b2J1Zi90eXBlcy9rbm93bi9kdXJhdGlvbnBi+AEBogIDR1BCqgIeR29vZ2xlLlByb3RvYnVmLldlbGxLbm93blR5cGVzYgZwcm90bzM=",
	})
}